import type { WorkspaceData } from './dashboardModel';

export const workspaceData: WorkspaceData = {
  metrics: [
    {
      id: 'delivery',
      label: '本周交付',
      value: '24',
      hint: '较上周多 6 项',
      tone: 'accent',
    },
    {
      id: 'coverage',
      label: '自动化覆盖',
      value: '92%',
      hint: '单测与 smoke 已联动',
      tone: 'ok',
    },
    {
      id: 'risk',
      label: '风险阻塞',
      value: '03',
      hint: '需要今天内处理',
      tone: 'danger',
    },
    {
      id: 'latency',
      label: '平均响应',
      value: '1.4s',
      hint: '近 24 小时下降 12%',
      tone: 'warn',
    },
  ],
  quickActions: [
    {
      id: 'review',
      label: '待评审',
      description: '集中处理高优先级改动与接口回归',
      count: '06',
    },
    {
      id: 'release',
      label: '待发布',
      description: '收敛已通过验证的发布批次',
      count: '03',
    },
    {
      id: 'alert',
      label: '告警处理',
      description: '查看 30 分钟内新增的风险信号',
      count: '02',
    },
  ],
  activity: [
    {
      id: 'activity-1',
      team: '平台组',
      title: '消息路由热修完成回归',
      summary: '接口路径 smoke 与前端调用映射已重新锁定，等待合并。',
      time: '3 分钟前',
      tone: 'review',
    },
    {
      id: 'activity-2',
      team: '设计组',
      title: '移动端壳层动画已接入',
      summary: '首屏卡片采用 stagger reveal，详情抽屉支持手势式关闭节奏。',
      time: '14 分钟前',
      tone: 'running',
    },
    {
      id: 'activity-3',
      team: '运维组',
      title: '夜间构建有 1 个风险项',
      summary: 'Electron 打包日志出现签名缺失，需要补充环境变量后重跑。',
      time: '27 分钟前',
      tone: 'risk',
    },
  ],
  queues: [
    { id: 'queue-draft', label: '待整理', count: 8, change: '+3' },
    { id: 'queue-running', label: '执行中', count: 11, change: '+1' },
    { id: 'queue-review', label: '待评审', count: 6, change: '-2' },
    { id: 'queue-risk', label: '有风险', count: 3, change: '+1' },
  ],
  focus: [
    {
      id: 'focus-1',
      title: 'Agent 控制台重构',
      owner: '王简',
      progress: 74,
      due: '今天 18:30',
      tone: 'running',
    },
    {
      id: 'focus-2',
      title: '接口 smoke 补齐',
      owner: '球球',
      progress: 88,
      due: '今天 21:00',
      tone: 'review',
    },
    {
      id: 'focus-3',
      title: 'Electron 发布验证',
      owner: '阿青',
      progress: 31,
      due: '明天 10:00',
      tone: 'risk',
    },
  ],
  workItems: [
    {
      id: 'router-upgrade',
      name: '路由回归验证',
      owner: '球球',
      stage: 'review',
      priority: 'P0',
      progress: 82,
      due: '今天 22:00',
      summary: '锁定接口路径和 smoke 覆盖，避免前后端路径漂移导致 404。',
      tags: ['测试', '接口', 'Smoke'],
      timeline: [
        { id: 'router-1', label: '16:10', detail: '补齐 server 端点清单回归测试' },
        { id: 'router-2', label: '17:20', detail: '校对 client 调用路径与 method' },
        { id: 'router-3', label: '18:05', detail: '待确认总构建产物与 smoke 一致' },
      ],
    },
    {
      id: 'mobile-shell',
      name: '移动端壳层优化',
      owner: '阿青',
      stage: 'running',
      priority: 'P1',
      progress: 46,
      due: '明天 10:00',
      summary: '首页卡片与详情抽屉采用移动端优先布局，保证单手操作路径清晰。',
      tags: ['移动端', '布局', '动画'],
      timeline: [
        { id: 'mobile-1', label: '15:40', detail: '导航入口收敛到顶部操作条' },
        { id: 'mobile-2', label: '17:00', detail: '加入抽屉进入与离场过渡' },
        { id: 'mobile-3', label: '进行中', detail: '补齐窄屏可读性与点击热区' },
      ],
    },
    {
      id: 'workspace-copy',
      name: '中文错误文案统一',
      owner: '林溪',
      stage: 'draft',
      priority: 'P1',
      progress: 18,
      due: '明天 15:00',
      summary: '清理 UI 文案与后端错因透出，避免英文提示影响排障效率。',
      tags: ['文案', '错误处理'],
      timeline: [
        { id: 'copy-1', label: '待开始', detail: '梳理 http helper 与 toast 消息来源' },
      ],
    },
    {
      id: 'electron-release',
      name: 'Electron 发布验收',
      owner: '赵越',
      stage: 'risk',
      priority: 'P0',
      progress: 31,
      due: '今天 23:30',
      summary: 'macOS 打包仍有签名环境不完整问题，需要先解决再出安装包。',
      tags: ['发布', 'Electron', '签名'],
      timeline: [
        { id: 'release-1', label: '14:20', detail: '识别签名证书缺口' },
        { id: 'release-2', label: '16:50', detail: '增加失败原因透传' },
        { id: 'release-3', label: '阻塞中', detail: '等待补齐签名配置后重跑' },
      ],
    },
  ],
};
